### ISSUE TITLE
Apps instance [***] is the subject of a conflict

### ISSUE THREAD

**Issue by MathieuUrstein** [google-github-actions/deploy-appengine#156]
### Question
I'm receiving the following error:
```
Apps instance [***] is the subject of a conflict: Cannot operate on apps/*** because an operation is already in progress for apps/***
```
A little bit after `google-github-actions/deploy-appengine@main` runs
```
gcloud app deploy --quiet ***.yaml dispatch.yaml --project *** --version *** --promote
```
I know this is not an issue with `google-github-actions/deploy-appengine` but it's the underlying `gcloud app deploy` command.

I found out it's related to the fact that I deploy two apps sequentially using two `google-github-actions/deploy-appengine@main` jobs. It does happen 20% of the time and there is a random delay for GAE to be ready again for a `gcloud app deploy` on the same project sharing instances. Of course the issue always happen on the second job.

Is there something I could do except add a random `sleep` to my jobs to resolve the issue consistently?

**Comment by sethvargo** [comment]
If the apps are in the same workflow, you can [make sure they don't run in parallel](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) or explicitly mark one as depending on the other (so they run in serial).

**Comment by MathieuUrstein** [comment]
Hello @sethvargo, thanks for your insight. Unfortunately, I'm already doing that. I found out that when `gcloud app deploy` finishes, you have not guarantee that GAE is ready for another deployment.

**Comment by sethvargo** [comment]
That sounds like it could be a bug in the gcloud CLI then. Unfortunately there's not much we can do in this GitHub Action to fix that. Have you filed a bug via [`gcloud feedback`](https://cloud.google.com/sdk/gcloud/reference/feedback)?

**Comment by MathieuUrstein** [comment]
I'm going to do a feedback then. Thanks.
