### ISSUE TITLE
This actions doesn't have the `working_directory` parameter anymore

### ISSUE THREAD

**Issue by Arseniyyy** [google-github-actions/deploy-appengine#160]
### TL;DR
When trying to use the `working_directory` parameter, GH actions says:
```
Warning: Unexpected input(s) 'working_directory', valid inputs are ['project_id', 'deliverables', 'image_url', 'version', 'promote', 'credentials']
```

**Comment by averikitsch** [comment]
Hi @Arseniyyy, what release version are you using or are your using `google-github-actions/deploy-appengine@main`?

**Comment by Arseniyyy** [comment]
@averikitsch hey sorry I was using v0.2.0
