### ISSUE TITLE
Docs don't specify how to set up identity federation

### ISSUE THREAD

**Issue by joeyparrish** [google-github-actions/deploy-appengine#246]
### TL;DR

The docs don't specify how to set up identity federation.  There's not nearly enough information to get started.  I found details here:

https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions

Can we please either link to this in the README or import the information into the README where it can be kept up-to-date?

### Action YAML

```yaml
# N/A
```

**Comment by joeyparrish** [comment]
Even better, I finally found the docs I wanted in the auth action repo: https://github.com/google-github-actions/auth#setting-up-workload-identity-federation

Can we please link to that?

**Comment by sethvargo** [comment]
Hi @joeyparrish thank you for opening an issue. The [Authorization section of the README](https://github.com/google-github-actions/deploy-appengine#authorization) links to the `auth` action which is where this is centrally located. Do you have a suggestion of where else we could put the link?

**Comment by joeyparrish** [comment]
I think a link to the specific section on workload identity federation would have saved me a bunch of time and effort.
