### ISSUE TITLE
Automatic artifact cleanup

### ISSUE THREAD

**Issue by Nerdsie** [google-github-actions/deploy-appengine#344]
### TL;DR

If my understanding is correct, as the project is being deployed, artifacts are created and stored in Google Cloud Storage, in the us.artifacts/ folder.  Once the app is deployed however, all of these artifacts can be deleted and the app continues to run.  It would be useful to have a flag of some sort that automatically deletes any generated artifacts, and it might be nice to add a small section to the README mentioning these artifacts

**Comment by sethvargo** [comment]
Hi @Nerdsie - this GitHub Action is a small wrapper around the [gcloud CLI](https://cloud.google.com/sdk/gcloud). If that functionality exists in gcloud, we'd be happy to add it. If it does not, you can request it from the gcloud team by opening an issue by following the instructions at https://cloud.google.com/sdk/docs/getting-support.
