### ISSUE TITLE
Promote flag default doesn't agree with docs

### ISSUE THREAD

**Issue by joeyparrish** [google-github-actions/deploy-appengine#361]
### TL;DR

The promote flag is documented as defaulting to true, but actually defaults to false.

### Expected behavior

In v0, it was defaulted to true with:

```ts
    const promote = getInput('promote');
    // ...
    if (promote === '' || String(promote).toLowerCase() === 'true') {
      appDeployCmd.push('--promote');
    } else {
      appDeployCmd.push('--no-promote');
    }
```

### Observed behavior

In v2, there is no explicit default anywhere, so the parseBoolean default of `false` takes over.

```ts
    const promote = parseBoolean(getInput('promote'));
    // ...
    if (promote) {
      appDeployCmd.push('--promote');
    } else {
      appDeployCmd.push('--no-promote');
    }
```

### Action YAML

```yaml
# N/A AFAICT
```

### Log output

```text
# N/A AFAICT
```

### Additional information

If the docs are correct, I believe the fix could be as simple as changing:

```ts
    const promote = parseBoolean(getInput('promote'));
```

to:

```ts
    const promote = parseBoolean(getInput('promote'), /* default= */ true);
```

If the docs are wrong, then the obvious fix is to correct the docs.

**Comment by sethvargo** [comment]
The [default value in the `action.yml`](https://github.com/google-github-actions/deploy-appengine/blob/f53a32be19aee208391f7b60ec65be85bd494adf/action.yml#L57) is true. Are you seeing a different behavior?

**Comment by joeyparrish** [comment]
Yes.  I was passing a value that happened to be blank due to a dumb workflow bug.

```yaml
    with:
      promote: ${ env.APPSPOT_PROMOTE }
```

That variable was meant to be "true" or "false", but it was left out of the environment entirely.  It would appear that the default in action.yml was not used in this case.

This didn't become obvious until I upgraded from v0 to v2, since v0 had the default implemented explicitly in TypeScript.

**Comment by sethvargo** [comment]
Right - if you pass in a value, it will use the empty string (whereas not providing a value uses the default).

**Comment by joeyparrish** [comment]
Thanks!
